### ISSUE TITLE
Calyx Info is outdated

### ISSUE THREAD

**Issue by catwithbanana** [privacyguides/privacyguides.org#585]
## Description
Calyx is now on Android 12, meaning the warning about being stuck on the October security patch is no longer accurate. I believe it is now up to date with security patches.

Also, the issues with Datura firewall were fixed in Android 12, so that warning should also be removed.

**URL of affected page:**
https://privacyguides.org/android/

**Comment by tommytran732** [comment]
I will update the warning later today or tomorrow. Their Chromium webview is still outdated however.

The leaks have been fixed it seems, but I haven't found any docs for it yet, so idk how it handles indirect connections via intents or if an app can just bypass the firewall using a local proxy.

**Comment by dngray** [comment]
I think we've resolved this, still their beta isn't yet stable it's getting close only 3 known issues remaining!

https://www.reddit.com/r/CalyxOS/comments/sorgck/android_12_february_2022_security_update/
